<?php 
    require_once '../Model/connect.php'; 
    require_once '../Controller/ConnectController.php';
        $objControl = new ConnectController();

        $objControl->verificarlogin();

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title><?php echo $titulo1; ?></title>
        <!-- BOOTSTRAP STYLES-->
        <link href="../assets/css/bootstrap.css" rel="stylesheet" />
        <!-- FONTAWESOME STYLES-->
        <link href="../assets/css/font-awesome.css" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
        <link href="../assets/css/custom.css" rel="stylesheet" />
        <!-- GOOGLE FONTS-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
        
        <script src="../ckeditor/ckeditor.js"></script>
        <script>
            function validarSenha() {
                NovaSenha = document.FormSenha.senha.value;
                CNovaSenha = document.FormSenha.C_senha.value;
                if (NovaSenha != CNovaSenha) {
                    alert("Senhas diferentes!\ \n Favor digitar senhas iguais");
                    return false;
                }
                return true;
            }

            function confirmar() {
                // só permitirá o envio se o usuário responder OK
                var resposta = window.confirm("Deseja mesmo" +
                        " excluir este registro?");
                if (resposta)
                    return true;
                else
                    return false;
            }
        </script>
    </head>
    <body>



        <div id="wrapper">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="adjust-nav">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">
                            <img src="../assets/img/logo.png" />
                        </a>
                    </div>
                    <span class="logout-spn">
                        <a href="Usuario_LogOut.php" style="color:#fff;">Sair de <?php echo $_SESSION['usuario'];?></a>  

                    </span>
                </div>
            </div>
            <!-- /. NAV TOP  -->
            <nav class="navbar-default navbar-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="main-menu">


                        <li >
                            <a href="index.php" ><i class="fa fa-desktop "></i>Dashboard <span class="badge">Included</span></a>
                        </li>


                        <li>
                            <a href="ui.html"><i class="fa fa-table "></i>UI Elements  <span class="badge">Included</span></a>
                        </li>
                        <li class="active-link">
                            <a href="blank.html"><i class="fa fa-edit "></i>Blank Page  <span class="badge">Included</span></a>
                        </li>



                        <li>
                            <a href="teste.php"><i class="fa fa-qrcode "></i>Teste</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o"></i>My Link Two</a>
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-edit "></i>My Link Three </a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table "></i>My Link Four</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-edit "></i>My Link Five </a>
                        </li>
                    </ul>
                </div>

            </nav>
            <!-- /. NAV SIDE  -->
            <div id="page-wrapper" >
                <div id="page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <h2><?php echo $titulo2; ?></h2>   
                        </div>
                    </div>  
                    <hr />